fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      # language_version: python3.8
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.4.0
    hooks:
    - id: autoflake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=file:.clang-format", "-i"]
      # - id: clang-tidy
        # # args: [--config-file=.clang-tidy, --system-headers, --fix, --fix-errors]
      # - id: cppcheck
      # - id: include-what-you-use
  # - repo: https://github.com/cheshirekow/cmake-format-precommit
  #   rev: v0.6.13
  #   hooks:
  #     - id: cmake-format
  #     # - id: cmake-lint
