fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
    - id: black
      args: [--line-length=120]
      # language_version: python3.8
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    - id: autoflake
      args: [--remove-all-unused-imports, --remove-duplicate-keys, --remove-unused-variables, --in-place]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: [
        "--max-line-length=120",
        "--ignore=E203,E266,E501,W503,F403,F401",
        "--max-complexity=24",
        "--select=B,C,E,F,W,T4,B9"
      ]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=file:.clang-format", "-i"]
      # - id: include-what-you-use
