fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      # language_version: python3.8
      args: [
        "--config=tools/pyproject.toml",
      ]
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.4.0
    hooks:
    - id: autoflake8
      args: [
        "--config=tools/pyproject.toml",
      ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: [
        "--config=tools/pyproject.toml",
      ]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=file:.clang-format", "-i"]
      # - id: include-what-you-use
