version: '3.8'

services:
  vulkan-dev:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    ipc: host
    network_mode: host
